name: Build Android APK

on:
  push:
    branches: [ "main" ] # Akan otomatis build setiap ada kode baru
  workflow_dispatch: # Memungkinkan Anda memicu build secara manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17' # Android modern menggunakan Java 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iderVPS-app
        path: app/build/outputs/apk/debug/app-debug.apk
